/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116219-gac6263945a-20240710"
#endif /* AVUTIL_FFVERSION_H */
