/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116133-g03175b587c-20240704"
#endif /* AVUTIL_FFVERSION_H */
